# =====================================================================
#  Undo the rejected commit, fix .gitignore, commit properly, push
#  Written by SWGReturn (Claude), 2026-08-15.
#
#  WHAT WENT WRONG
#  `git add -A` swept in MMOCoreORB/bin/databases -- the runtime Berkeley
#  DB. __db.001 is 628 MB; GitHub's hard limit is 100 MB, so the push was
#  rejected. The commit is LOCAL ONLY; nothing reached GitHub, so a soft
#  reset undoes it cleanly with no history rewrite.
#
#  TWO .gitignore PROBLEMS FOUND
#   1. bin/databases is not ignored  -> the 628 MB upload.
#   2. `*.sh` IS ignored -> patches/apply.sh, the script that keeps the
#      engine3 fix alive across submodule updates, would have been
#      silently left out of the repo. Needs an explicit negation.
#
#  (bin/conf/* is already ignored, so config-local.lua and the database
#   password were never in the commit. Good, given the repo is going public.)
# =====================================================================

$ErrorActionPreference = 'Continue'
$Distro = 'Ubuntu-24.04'
function Say($m, $c = 'Gray') { Write-Host $m -ForegroundColor $c }

Clear-Host
Say ''
Say '  ############################################################' Cyan
Say '  #   Undo, fix, and re-commit properly                      #' Cyan
Say '  ############################################################' Cyan
Say ''

$prep = @'
#!/usr/bin/env bash
set -uo pipefail
REPO=/mnt/c/SWGGenesis
cd "$REPO" || exit 1

echo "======== 1. undo the rejected commit ========"
echo "  HEAD is currently:"
git log --oneline -1
if git log -1 --pretty=%s | grep -q "Rebuild on a fresh Windows install"; then
    git reset --soft HEAD~1 && echo "  soft-reset: commit undone, working tree untouched"
    git reset >/dev/null 2>&1 && echo "  unstaged everything"
else
    echo "  (that commit is not at HEAD - leaving history alone)"
    git reset >/dev/null 2>&1
fi
echo "  HEAD is now:"
git log --oneline -1

echo
echo "======== 2. fix .gitignore ========"
if ! grep -q "SWGGENESIS SETUP 2026-08-15" .gitignore; then
cat >> .gitignore <<'IGN'

# ===== SWGGENESIS SETUP 2026-08-15 =====
# The runtime object database. Regenerated by the server, and enormous:
# __db.001 alone is 628 MB against GitHub's 100 MB hard limit. This is
# what got a push rejected on 2026-08-15.
MMOCoreORB/bin/databases/

# Setup and build logs written into the repo root by the installer scripts.
setup_log.txt
setup_wsl_log.txt
finish_build_log.txt
fix_rebuild_log.txt
copy_log.txt
client_setup_log.txt
relay-autostart.log
server_relay/relay.log
backups/
panel_settings.ini
.genesis_timings
.genesis_timing_marks
_commit_prep.sh
_commit_do.sh

# `*.sh` above is a very broad rule and it swallows our own patch tooling.
# patches/apply.sh re-applies the engine3 fixes after a submodule update;
# without it, a fresh clone gets the patch file and no way to apply it,
# and the server dies ~10 minutes into every boot. Keep it tracked.
!patches/apply.sh
IGN
echo "  appended the new rules"
else
    echo "  already present, skipping"
fi

# In case any of it was ever staged or tracked
git rm -r --cached --quiet MMOCoreORB/bin/databases >/dev/null 2>&1 && echo "  untracked bin/databases" || true

echo
echo "======== 3. stage deliberately (no more add -A) ========"
# tracked files that changed or were removed
git add -u
# the things we actually created
git add .gitignore
git add -f patches/apply.sh patches/engine3-time-overflow.patch 2>/dev/null
git add swggenesis_menu.py SWGGenesisControlPanel.ahk run_backup.cmd 2>/dev/null
git add server_relay/relay.py "server_relay/START RELAY.cmd" "server_relay/INSTALL RELAY AUTOSTART.cmd" 2>/dev/null
git add ./*.ps1 ./*.cmd 2>/dev/null

echo
echo "======== 4. what is staged now ========"
git diff --cached --stat | tail -30
echo
echo "  files staged: $(git diff --cached --name-only | wc -l)"
echo
echo "  --- anything staged over 20 MB? ---"
git diff --cached --name-only -z | while IFS= read -r -d '' f; do
    [ -f "$f" ] || continue
    sz=$(stat -c%s "$f" 2>/dev/null || echo 0)
    if [ "$sz" -gt 20000000 ]; then echo "    !! $f  ($((sz/1000000)) MB)"; fi
done
echo "  (nothing listed above = safe to push)"
echo
echo "  --- confirming apply.sh made it in ---"
git diff --cached --name-only | grep -E "patches/" || echo "    !! patches/ NOT staged"
'@

[IO.File]::WriteAllText('C:\SWGGenesis\_fix_prep.sh', ($prep -replace "`r`n", "`n"))
& wsl.exe -d $Distro -u root -- bash /mnt/c/SWGGenesis/_fix_prep.sh 2>&1 | ForEach-Object { Write-Host $_ }

Say ''
Say '  ============================================================' Yellow
Say '   Nothing committed or pushed yet. Check the size list above.' Yellow
Say '  ============================================================' Yellow
Say ''
$ans = Read-Host '  Type YES to commit and push'
if ($ans -ne 'YES') { Say ''; Say '  Cancelled.' Yellow; Say ''; return }

$doit = @'
#!/usr/bin/env bash
set -uo pipefail
cd /mnt/c/SWGGenesis || exit 1
git config user.name  >/dev/null 2>&1 || git config user.name  "SWGfan"
git config user.email >/dev/null 2>&1 || git config user.email "nicholaswill86@gmail.com"

git commit -F - <<'MSG'
Rebuild on fresh Windows; fix a real buffer overflow in engine3

Machine reinstalled from bare Windows - no WSL, toolchain or MySQL.
Rebuilt end to end and verified in-game.

engine3 buffer overflow (the important one)
  system/lang/Time.h getFormattedTimeFull() computed the space left in a
  128-byte buffer as `len -= ret - 1`, one byte more than actually remains
  at &buf[ret]: snprintf was told 110 bytes when 109 were free. Ubuntu
  24.04 defaults to -D_FORTIFY_SOURCE=3, so glibc detected the overrun and
  called abort(). The server died ~643s into every boot, in
  OnlinePlayerLogTask -> logOnlinePlayers -> getFormattedTimeFull.
  Debian does not fortify by default, so every previous build wrote past
  that buffer silently. The fix is one character: `len -= ret;`

  Carried as patches/engine3-time-overflow.patch rather than an edit inside
  the submodule, because `git submodule update` would revert it and
  reintroduce the crash with nothing pointing at the cause.
  patches/apply.sh re-applies all patches idempotently and should run
  before every build.

build
  -DENABLE_BUILD_CLIENT=OFF. core3client does not compile against the
  pinned engine3 (ClientCore.h inherits Core, which system/lang.h no
  longer declares) and, being in the default `all` target, its failure
  aborts make before core3 links. Upstream ships this switch, so source
  divergence stays at zero.

tooling
  Repo moved off the spinning HDD to the C: SSD; ~39 hardcoded D: paths
  repointed across swggenesis_menu.py, SWGGenesisControlPanel.ahk and
  run_backup.cmd. D:\Launcher references deliberately untouched.
  WSL distro Debian -> Ubuntu-24.04, named explicitly in the panel and in
  run_backup.cmd - missing either would silently break every panel button
  and the nightly scheduled backup.
  Windows username no longer hardcoded (A_UserName).
  Client folder is now C:\SWGEmu rather than the launcher install.
  Installer scripts added at the repo root.

config
  Core3.ZonesEnabled override removed: a zone subset segfaults genesis in
  ResourceSpawner::ghDumpAll(), which hardcodes ten planets and
  dereferences getZoneResourceList() with no null check.

server_relay
  UDP relay reads its ports from config-local.lua instead of the hardcoded
  44xxx block, and names the WSL distro explicitly. A relay on the wrong
  ports forwards nothing and reports nothing - UDP login just hangs.

gitignore
  MMOCoreORB/bin/databases/ ignored - the runtime object DB, 628 MB, which
  got a push rejected. Installer logs ignored. Negation added for
  patches/apply.sh, which the pre-existing broad `*.sh` rule was silently
  excluding.
MSG

echo
echo "======== pushing ========"
git push origin HEAD
rc=$?
echo
if [ $rc -eq 0 ]; then echo "PUSH OK"; git log --oneline -1; else echo "!! push failed (exit $rc)"; fi
exit $rc
'@

[IO.File]::WriteAllText('C:\SWGGenesis\_fix_do.sh', ($doit -replace "`r`n", "`n"))
& wsl.exe -d $Distro -u root -- bash /mnt/c/SWGGenesis/_fix_do.sh 2>&1 | ForEach-Object { Write-Host $_ }

Say ''
if ($LASTEXITCODE -eq 0) { Say '   Committed and pushed.' Green } else { Say '   Push did not complete.' Yellow }
Say ''
