# =====================================================================
#  SWGGenesis: move the repo off the D: HDD onto the C: SSD
#  Written by SWGReturn (Claude), 2026-08-15.
#
#  Copies D:\SWGGenesis  ->  C:\SWGGenesis
#  Skips anything that gets regenerated by a rebuild, because a build
#  directory has the OLD absolute paths (/mnt/d/...) baked into its
#  CMake cache -- carrying it across would poison the first build on C:.
#
#  Nothing on D: is deleted. This is a copy, not a move.
# =====================================================================

$ErrorActionPreference = 'Stop'

$Src = 'D:\SWGGenesis'
$Dst = 'C:\SWGGenesis'
$Log = 'C:\SWGGenesis\move_log.txt'

# Directories that are pure build output / disposable state.
$SkipDirs = @(
    'build',                    # CMake build tree - has /mnt/d paths in its cache
    'databases',                # object DB (characters/items) - expendable, per Nick
    '.git-rewrite',             # leftover filter-branch scratch
    '__pycache__',
    '_idl_scratch_to_delete'
)

# Files that a rebuild reproduces, or that are just noise.
$SkipFiles = @(
    'core3',                    # 972 MB binary - rebuilt on C:
    'core3client',
    'testsuite3',
    'console.log',
    'console.log.prev',
    '*.bak',
    '*.bak-*',
    '*.20*.bak'
)

function Say($msg, $colour = 'Gray') { Write-Host $msg -ForegroundColor $colour }

Clear-Host
Say ''
Say '  ============================================================' Cyan
Say '   SWGGenesis  ->  C: SSD' Cyan
Say '  ============================================================' Cyan
Say ''

# --- sanity ----------------------------------------------------------
if (-not (Test-Path $Src)) {
    Say "  ERROR: $Src does not exist. Nothing to copy." Red
    Say ''
    return
}

# --- measure ---------------------------------------------------------
Say '  Measuring. On a spinning disk this takes a minute -- please wait.'
Say ''

$all = Get-ChildItem -Path $Src -Recurse -Force -File -ErrorAction SilentlyContinue

$keep = $all | Where-Object {
    $rel = $_.FullName.Substring($Src.Length).TrimStart('\')
    $parts = $rel -split '\\'
    $inSkippedDir = $false
    foreach ($p in $parts[0..([Math]::Max(0, $parts.Count - 2))]) {
        if ($SkipDirs -contains $p) { $inSkippedDir = $true; break }
    }
    if ($inSkippedDir) { return $false }
    foreach ($pat in $SkipFiles) { if ($_.Name -like $pat) { return $false } }
    return $true
}

$totalGB = [math]::Round((($all  | Measure-Object Length -Sum).Sum) / 1GB, 2)
$copyGB  = [math]::Round((($keep | Measure-Object Length -Sum).Sum) / 1GB, 2)
$freeGB  = [math]::Round((Get-PSDrive C).Free / 1GB, 2)

Say ("  Whole D:\SWGGenesis tree ...... {0,8:N2} GB  ({1:N0} files)" -f $totalGB, $all.Count)
Say ("  Actually needs copying ........ {0,8:N2} GB  ({1:N0} files)" -f $copyGB, $keep.Count) Green
Say ("  Free space on C: .............. {0,8:N2} GB" -f $freeGB) $(if ($freeGB -gt ($copyGB * 1.5)) { 'Green' } else { 'Yellow' })
Say ''

# Leave headroom: the copy itself, plus room for a build tree afterwards
# (the build directory alone runs well over 10 GB).
$needGB = $copyGB + 25

if ($freeGB -lt $copyGB + 2) {
    Say '  STOP: C: does not have room for the copy itself.' Red
    Say ("  Need at least {0:N2} GB free, have {1:N2} GB." -f ($copyGB + 2), $freeGB) Red
    Say ''
    Say '  Tell Claude this number and we will work out what to clear.' Yellow
    Say ''
    return
}

if ($freeGB -lt $needGB) {
    Say ("  WARNING: the copy fits, but a rebuild afterwards needs roughly" ) Yellow
    Say ("  {0:N0} GB more for the build tree. You have {1:N2} GB." -f 25, $freeGB) Yellow
    Say '  You can continue -- just be aware the build may run out of room.' Yellow
    Say ''
}

Say '  Skipping (all of it regenerated by a rebuild):' DarkGray
foreach ($d in $SkipDirs)  { Say ("    dir   {0}" -f $d) DarkGray }
foreach ($f in $SkipFiles) { Say ("    file  {0}" -f $f) DarkGray }
Say ''
Say '  Nothing on D: is deleted. This is a copy.' DarkGray
Say ''

$answer = Read-Host '  Type  YES  to start the copy'
if ($answer -ne 'YES') {
    Say ''
    Say '  Cancelled. Nothing was changed.' Yellow
    Say ''
    return
}

# --- copy ------------------------------------------------------------
Say ''
Say '  Copying. Reading from a spinning disk, so this is not fast.' Cyan
Say '  You can leave it running.' Cyan
Say ''

New-Item -ItemType Directory -Force -Path $Dst | Out-Null
if (Test-Path $Log) { Remove-Item $Log -Force }

$args = @(
    $Src, $Dst,
    '/E',            # include subdirs, including empty ones
    '/R:2', '/W:5',  # 2 retries, 5s apart -- do not hang on a bad sector
    '/NP',           # no per-file percentage spam
    '/NFL', '/NDL',  # no per-file / per-dir listing; summary only
    '/TEE',
    "/LOG+:$Log"
)
foreach ($d in $SkipDirs)  { $args += '/XD'; $args += $d }
foreach ($f in $SkipFiles) { $args += '/XF'; $args += $f }

$started = Get-Date
& robocopy.exe @args
$code = $LASTEXITCODE
$mins = [math]::Round(((Get-Date) - $started).TotalMinutes, 1)

Say ''
Say '  ============================================================' Cyan

# robocopy: 0-7 are success//informational, 8+ are real failures.
if ($code -lt 8) {
    Say ("   COPY OK  --  finished in {0} minutes (robocopy code {1})" -f $mins, $code) Green
    Say ''
    $newGB = [math]::Round((((Get-ChildItem -Path $Dst -Recurse -Force -File -ErrorAction SilentlyContinue) |
                             Measure-Object Length -Sum).Sum) / 1GB, 2)
    Say ("   C:\SWGGenesis is now {0:N2} GB" -f $newGB) Green
    Say ''
    Say '   Next: tell Claude it is done. Nothing on D: was touched, so' Gray
    Say '   the old copy is still there as a fallback until you delete it.' Gray
} else {
    Say ("   COPY FAILED  --  robocopy exit code {0}" -f $code) Red
    Say ''
    Say '   Tell Claude the code above. The full log is at:' Yellow
    Say ("   {0}" -f $Log) Yellow
}

Say '  ============================================================' Cyan
Say ''
